name: Run All Tests

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  tests:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Gradle cache
        uses: gradle/gradle-build-action@v2

      - name: AVD cache
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-27

      - name: create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 27
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      - name: Assemble Tests
        run: ./gradlew assembleAffectedAndroidTests -Paffected_module_detector.enable

      - name: Run All Affected Unit Tests
        run: ./gradlew runAffectedUnitTests -Paffected_module_detector.enable

      - name: Run All Affected Android Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 27
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: ./gradlew runAffectedAndroidTests -Paffected_module_detector.enable
